### ISSUE TITLE
Persisting into database

### ISSUE THREAD

**Issue by mtangoo** [brick/money#16]
Hi,
Thank you for the library. I was reading the doc and its comprehensive except it does not provide any recommendation as to what should be the field type (database column data type that can work better with library). This will help avert confusion as reading the answers on the internet ends up confusing newbees. Also comment on fields like Postgresql Money data type would be helpful.

Cheers!

**Comment by BenMorel** [comment]
Hi, this could be a nice thing to add to the doc indeed.

For the time being, I can only tell you that I personally store my monies in the database as an integer representing the amount in minor units (cents), and optionally a `CHAR(3)` for the currency if the application uses multiple currencies (otherwise the currency is hardcoded in the app).

You can get the amount in minor units this way, as an integer:

    $money->getMinorAmount()->toInt();

And you can retrieve a Money from an integer stored in the database using:

    Money::ofMinor($integerAmount, 'USD');

I cannot comment on the money data type, as I don't use Postgresql. But I will surely look at it if I add this doc later on!

**Comment by mtangoo** [comment]
Thanks for the quick response. 
That cleared a lot of fogs. I have one more question though.

I was thinking about using NUMERIC(15, 6) to store full data. What do think of performance given you are the author and knows internals of the library?

**Comment by mtangoo** [comment]
I will close this for now, since main issue is solved. If you get time you can address the other one too!
Thank you!

**Comment by BenMorel** [comment]
The problem with NUMERIC is not performance (NUMERIC and INTEGER should perform equally well), it is that the scale is fixed. This is OK if you're dealing with a single currency, but as soon as you want support for multiple currencies, this can become a problem as they don't all have 2 fraction digits. JPY for example has 0 fraction digits, while TND has 3 digits. You can use a NUMERIC that has the largest scale, of course, but my preference is to deal with integers here, and the scale is implied by the currency.

**Comment by mtangoo** [comment]
I see! Yours is the most logical way.
Thank you for your time!

**Comment by BenMorel** [comment]
Now documented 😉

https://github.com/brick/money#storing-the-monies-in-the-database
