### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by martinknor** [brick/money#2]
Can you make release on packagist?

**Comment by BenMorel** [comment]
Duplicate of (long overdue) #1 !

I'm note quite ready yet to tag a release, as there are still several issues that bother me, and I feel like the API is going to change again. I'm happy to list these issues somewhere though, if some of you want to jump in and help me clarify my mind :)

**Comment by martinknor** [comment]
I will be glad to improve this library. Please send me list of these issues and i will try to help you.

**Comment by jiripudil** [comment]
@BenMorel How about opening Github issues to start some discussion? I've been using this library for some time and I'd love to help it make it to a stable release soon 🙂

**Comment by BenMorel** [comment]
Hi guys, sorry for the wait.

Here are the things that bother me currently with this library:

- #3 [Scales and Money classes](https://github.com/brick/money/issues/3)
- #4 [Money contexts](https://github.com/brick/money/issues/4)
- #5 [Custom currencies](https://github.com/brick/money/issues/5)
- #6 [Implementation / performance](https://github.com/brick/money/issues/6)

Please feel free to comment on the issues above!

It was actually good for me to take the time to make an inventory of these issues; while writing them, many things became more clear in my mind, and I already have an idea of the direction I want the library to take for the first release. That's why you'll probably find the issues somewhat opinionated, but they're still exploring a few options, and I'm looking forward to get some external feedback! 👍

**Comment by BenMorel** [comment]
Pinging @fprochazka @VasekPurchart @jkuchar from #1!

**Comment by BenMorel** [comment]
Version [0.1.0](https://github.com/brick/money/releases) released! :tada:

Special thanks to @jkuchar, @jiripudil, @VasekPurchart for the discussions in the issue tracker. They definitely helped moving this project in the right direction and getting the release ready!

Note that version 0.1 will be the only version to support PHP 5.6 and PHP 7.0. I did want to release this version to not leave PHP 5.6 users out: even though [active support for PHP 5.6 has been dropped](http://php.net/supported-versions.php), security fixes will still be provided for more than a year from now. So will version 0.1: I will fix any bug found on this version until the EOL of both PHP 5.6 and PHP 7.0 are reached (31 December 2018), but will not backport new features to this version.

I will release version 0.2 soon, with a [PHP 7.1 minimum requirement](https://gophp71.org/). The functionality will be exactly the same as in 0.1.

**Comment by jiripudil** [comment]
@BenMorel let me say a big thank you to you too! I loved the way you had moderated and facilitated the discussion, it was such a pleasant experience to participate in it. Looking forward to trying the new release soon!
