### ISSUE TITLE
Allocate method not working as expected. 

### ISSUE THREAD

**Issue by saffabook** [brick/money#73]
Am I misunderstanding the allocate function? 

I have a total of 100000 
I want to allocate this total and split it to the below percentages _(which add to 100%)_;
        $divided = $currentTotal->allocate(8.23, 91.77);

This gives me the values of **[8081, 91919]**

But 8.23% of 100000 should be **8230** not **8081**

Is there some error that I am doing?

**Comment by BenMorel** [comment]
Hi, `allocate()` uses integers as ratios:

```php
public function allocate(int ...$ratios) : array
```

https://github.com/brick/money/blob/0.7.0/src/Money.php#L513

If you pass integers instead of floats, you get the correct result:

```
$divided = $currentTotal->allocate(823, 9177); // [8230.00, 91770.00]
```

I would advise to use [strict_types](https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.strict) to avoid PHP making a lossy float-to-int conversion in this case.

**Comment by BenMorel** [comment]
You can now use integer, decimal, or rational numbers (as `BigNumber|int|string`) for ratios, plus you can now control the allocation algorithm through [AllocationMode](https://github.com/brick/money/blob/0.13.0/src/AllocationMode.php) in version [0.13.0](https://github.com/brick/money/releases/tag/0.13.0):

```php
$money = Money::of(100_000, 'EUR');
$money->allocate(['8.23', '91.77'], AllocationMode::FloorToFirst); // 8230.00, 91770.00
```
